name: adaptive_layout
description: "Provides adaptive layout sizes for creating responsive design"
version: 0.0.2
repository: https://github.com/pintusingh28/flutter-packages/tree/main/adaptive_layout
issue_tracker: https://github.com/pintusingh28/flutter-packages/issues

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
